# Generated by Django 6.0.6 on 2026-06-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantData',
            fields=[
                ('acc_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('course_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeesData',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.IntegerField(null=True)),
                ('student_id', models.IntegerField(null=True)),
                ('deposit_date', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('payment_Method', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.IntegerField(null=True)),
                ('course_name', models.CharField(max_length=100)),
                ('join_date', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('regno', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
