# Generated by Django 6.0.6 on 2026-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_accountantdata_coursedata_feesdata_studentcourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
            ],
        ),
    ]
